load_event_description:- 
	['auxiliary/compare'],
	['auxiliary/vesselStaticInfo'],
	['auxiliary/staticDataPredicates'],
	['auxiliary/typeSpeeds'],
	['auxiliary/thresholds'],
	['auxiliary/timeModel'],
	%assertFirstTimepoint,
	['event_description/rules'],
	['event_description/declarations'],
	['event_description/hierarchy'],
	['datasets/initialProbabilities'],
	assertInitialProbabilities.
